language: node_js
node_js:
 - "node"
script:
  - npm test -- --coverage --watchAll=false
before_install:
  - pip install --user codecov
after_success:
  - codecov --file coverage/lcov.info --disable search