language: node_js
node_js:
 - "node"
env:
  global:
    - CC_TEST_REPORTER_ID=GY46998
    - CODECOV_TOKEN="20b146b3-2331-42b4-a656-af25a618737f"
before_install:
  - pip install --user codecov
after_success:
  - codecov --file coverage/lcov.info --disable search